FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
COPY server ./server
COPY tsconfig*.json ./

RUN npm run prisma:generate
RUN npm run build:api

FROM node:20-alpine
WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/server/dist ./server/dist

ENV PORT=8787
EXPOSE 8787

CMD ["node", "server/dist/main.js"]

